keychain:
  applogic:
    algorithm: RS256
    value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyMG52ekF2NDc1SXFZZTcxT0ZONwpuZjJFdk1QUkZBUkFQRVhKem0yTTB6MTE2WUNESlZYeG53S3h2YTRSNzlzMzI1bDA1blpmYnk2eTBzWWxDMTZiCm1KcWFvWnNBaVZYTXNScG9kWHVHS2tSTWhpUlhRNTdZMXZxSVhidjh0czZlOUs1UTY4WXBOK3g3cVZpb2VFWWwKZS9rbG9jN29raTMwdlFZSDNzOVFnZkduMTZ6U29VNldwRm1UUEFxVWFYcThjSlVtYzV4RjJKTVFLNHlWVXFUQgprVVB2NWtoTCtweW9jVkczbXVWcUdTaU1OVlZJZ0dablJnMVlxb3BIbnh3K3lhayt2YWtVZ09JY1ZJQms5bWs0CjI3aWFyWUFkVTB0K1RSSUxRdG1OZjlSR0dyTTJTZ2gwV2VVSERwY2ZQdlE1Tm1FNzRNclBISEhOT1hQaHloU3YKeXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    
scopes:
  read_users:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
