keychain:
  applogic:
    algorithm: RS256
    value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4bFVjVHZYdjdoREZjT1RhdTl0ZwpFSmI5Wm9laVFuaHhFU1pIWlJ0d0VjM0xYRlNOMFluNTRTUlNuVDZicVF0dkQxMXZGNkIrTnRld2NhN3pRZFJQCmtUN2l1cTRiOXRQMnVTQ3pXMk1lZEswejYzWUJIVXZVQVIvQmw1dE9xYzVHMnBubXF5VEMyclFWdzh5VEVHWHMKMGJ6QzhLVlFlV3ptWmptaGdsdzEwMnk2c1VHRzBXc3N0WkZsRTlyY1dkYnB1Um5MbXE2WGR6RTdINGxHazhoZwpRYkdmLzdFSnZiTXRoVXhqek9hRXlRbHRlL0szZ0Q3b3Nkc1VlMy8xSGdpZmZRaGZyaWtQcmpDVm0wS2x0d1pBClBaOWJ3VWxJTkVTQUlZVklJM0lHLzBVbUN3MDBHbjJxRWxyaEdYQnN3V0MrZzY1WWwxOVU3RTQ2eFh6MS9OZUsKRHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    
scopes:
  read_users:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic
