window.env = {
    api: {
      authUrl: 'http://www.app.local/api/v2/barong',
      tradeUrl: 'http://www.app.local/api/v2/peatio',
      finexUrl: 'http://www.app.local/api/v2/finex',
      applogicUrl: 'http://www.app.local/api/v2/applogic',
      rangerUrl: 'ws://www.app.local/api/v2/ranger',
    },
    minutesUntilAutoLogout: '35',
    withCredentials: false,
    finex: false,
    gaTrackerKey: '',
    rangerReconnectPeriod: '1',
    msAlertDisplayTime: '5000',
    incrementalOrderBook: true,
    isResizable: false,
    isDraggable: false,
    languages: ['en', 'ru'],
    sessionCheckInterval: '15000',
    balancesFetchInterval: '3000',
    passwordEntropyStep: 14,
    showLanding: true,
    sentryEnabled: false,
    kycSteps: [
      'email',
      'phone',
      'profile',
      'document',
      'address',
    ],
};
